1344 MainProcess 2024-05-01 16:17:26,390
Traceback (most recent call last):
  File "D:\Python\Lib\site-packages\pyarmor\cli\__main__.py", line 764, in main
    main_entry(sys.argv[1:])
  File "D:\Python\Lib\site-packages\pyarmor\cli\__main__.py", line 752, in main_entry
    return args.func(ctx, args)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\pyarmor\cli\__main__.py", line 244, in cmd_gen
    builder.process(options)
  File "D:\Python\Lib\site-packages\pyarmor\cli\generate.py", line 173, in process
    self._obfuscate_scripts()
  File "D:\Python\Lib\site-packages\pyarmor\cli\generate.py", line 129, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\pyarmor\cli\core\__init__.py", line 106, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<maker>", line 713, in generate_obfuscated_script
  File "D:\Python\Lib\site-packages\pyarmor\cli\__init__.py", line 16, in process
    return meth(self, res, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<maker>", line 543, in process
  File "<maker>", line 549, in coserialize
  File "<maker>", line 594, in _build_ast_body
RuntimeError: out of license
